spring:
    application:
        name: User Service
    datasource:
        url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/quantumgrid?currentSchema=usercervice}
        username: ${JDBC_DATABASE_USERNAME:userservice}
        password: ${JDBC_DATABASE_PASSWORD:P4ssword!}
        hikari:
            maximum-pool-size: 15
            idle-timeout: 30000
            connection-timeout: 8000
            validation-timeout: 30000
    JPA:
        Hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
                id:
                    new_generator_mappings: true
    lifecycle:
        timeout-per-shutdown-phase: 30s
    main:
        banner-mode: off
        lazy-initialization: true
    servlet:
        multipart:
            max-file-size: 31MB
            max-request-size: 31MB

server:
    port: 8080
    shutdown: graceful
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true

management:
    health:
        livenessstate:
            enabled: true
        readinessstate:
            enabled: true
    endpoints:
        web:
            exposure:
                include: health,info,metrics,prometheus,httptrace,swagger-ui,openapi,shutdown,threaddump
        jmx:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
            enabled: true
            group:
                custom:
                    show-components: always
                    show-details: always
        metrics:
            enabled: true
        mappings:
            enabled: true
        shutdown:
            enabled: true
        prometheus:
            enabled: true
    server:
        port: 8081
    info:
        java:
            enabled: true
        git:
            mode: full
            enabled: true
        build:
            enabled: true
        env:
            enabled: true
        os:
            enabled: true
        defaults:
            enabled: true

springdoc:
    show-actuator: false
    use-management-port: false
    pathsToMatch: /api/**, /authenticate, /register
